# Generated by Django 5.1.4 on 2025-05-22 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('has_expiry', models.BooleanField(default=False)),
                ('has_entry_number', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date_removed', models.DateTimeField(auto_now_add=True)),
                ('ITEM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.itemmaster')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('expiry_date', models.DateField(null=True)),
                ('entry_number', models.IntegerField(null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('ITEM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.itemmaster')),
            ],
        ),
    ]
