# Generated by Django 5.1.4 on 2025-05-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_itemmaster_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsin',
            name='net_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
