# Generated by Django 5.1.4 on 2025-05-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_goodsin_net_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsin',
            name='entry_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goodsin',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
