# Generated by Django 5.1.4 on 2025-05-23 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_goodsin_entry_number_alter_goodsin_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsin',
            name='entry_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
