# Generated by Django 5.1.4 on 2025-05-23 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_goodsin_entry_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateField(auto_now_add=True)),
                ('predicted_quantity', models.IntegerField()),
                ('ITEM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.itemmaster')),
            ],
        ),
    ]
